# These are supported funding model platforms

github: slickgrid-stellar
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: slickgrid-stellar
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: # Replace with a single custom sponsorship URL
