version: 2
jobs:
  build:
    working_directory: ~/angular-slickgrid
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run:
          name: "Run Jest and Collect Coverage Reports"
          command: ./node_modules/.bin/jest --collectCoverage=true
      - store_artifacts:
          path: coverage
      - run:
          name: Upload coverage to Codecov
          command: ./node_modules/.bin/codecov --token="${CODECOV_TOKEN}"
test:
  post:
    - ./bin/codecov -f tests/jest-coverage/*.json
